"""Generate ~/Applications/TailCam.app — a real macOS app, no Xcode needed.

The bundle is three generated files: an Info.plist (plistlib), a zsh launcher
stub that execs this venv's Python with ``-m tailcam app``, and a .icns icon
packed in pure Python from the shipped PNGs. Everything is byte-for-byte
verifiable on a Linux CI box; the only macOS-side steps are the optional
ad-hoc codesign (best-effort here) and Launch Services picking the app up.

Deliberately NO NSCameraUsageDescription: the shell never opens cameras —
capture stays in the launchd venv Python, so existing TCC camera grants are
untouched by installing or reinstalling the app.
"""

from __future__ import annotations

import io
import plistlib
import shutil
import struct
import sys
from importlib import resources
from pathlib import Path

from tailcam.logging_setup import get_logger
from tailcam.proc import run as run_hidden

log = get_logger(__name__)

BUNDLE_ID = "com.tailcam.app"
APP_NAME = "TailCam"

# .icns entry types by pixel size (PNG payloads are valid for all of these).
_ICNS_TYPES = {16: b"icp4", 32: b"icp5", 128: b"ic07", 256: b"ic08", 512: b"ic09"}

_LAUNCHER = """#!/bin/zsh
# TailCam.app launcher — generated by `tailcam app install`. Points at the
# per-user venv; reinstalling TailCam regenerates this stub.
exec "{python}" -m tailcam app
"""


def app_dir(applications: Path | None = None) -> Path:
    base = applications or (Path.home() / "Applications")
    return base / f"{APP_NAME}.app"


def build_info_plist() -> dict:
    return {
        "CFBundleExecutable": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": _version(),
        "CFBundleIconFile": APP_NAME,
        # Menu-bar app: no Dock icon of its own; the webview window still
        # fronts normally when opened.
        "LSUIElement": True,
        "LSMinimumSystemVersion": "12.0",
        "NSHighResolutionCapable": True,
    }


def _version() -> str:
    from tailcam import __version__

    return __version__


def _icon_sources() -> list[tuple[int, bytes]]:
    """(size, png_bytes) pairs for the icns, resized from the shipped 512px
    mark with Pillow (always present via the [desktop] extra)."""
    src = resources.files("tailcam.desktop") / "assets" / "app-icon-512.png"
    png512 = src.read_bytes()
    out: list[tuple[int, bytes]] = [(512, png512)]
    try:
        from PIL import Image

        with Image.open(io.BytesIO(png512)) as img:
            for size in (16, 32, 128, 256):
                buf = io.BytesIO()
                img.resize((size, size), Image.Resampling.LANCZOS).save(buf, format="PNG")
                out.append((size, buf.getvalue()))
    except Exception as exc:  # pragma: no cover - Pillow missing/broken
        log.warning("icon resize unavailable (%s); packing 512px only", exc)
    return sorted(out)


def build_icns() -> bytes:
    """Pack PNG payloads into the ICNS container (magic + big-endian lengths)."""
    chunks = b""
    for size, png in _icon_sources():
        icns_type = _ICNS_TYPES.get(size)
        if icns_type is None:
            continue
        chunks += icns_type + struct.pack(">I", len(png) + 8) + png
    return b"icns" + struct.pack(">I", len(chunks) + 8) + chunks


def install_app(
    applications: Path | None = None, python: str | None = None
) -> Path:
    """Write (or refresh) TailCam.app. Idempotent; safe to re-run on upgrade."""
    bundle = app_dir(applications)
    contents = bundle / "Contents"
    macos = contents / "MacOS"
    res_dir = contents / "Resources"
    macos.mkdir(parents=True, exist_ok=True)
    res_dir.mkdir(parents=True, exist_ok=True)

    with (contents / "Info.plist").open("wb") as fh:
        plistlib.dump(build_info_plist(), fh)

    stub = macos / APP_NAME
    stub.write_text(_LAUNCHER.format(python=python or sys.executable))
    stub.chmod(0o755)

    (res_dir / f"{APP_NAME}.icns").write_bytes(build_icns())

    _codesign(bundle)
    log.info("installed %s", bundle)
    return bundle


def _codesign(bundle: Path) -> None:
    """Ad-hoc sign so Gatekeeper treats the generated bundle kindly. Best
    effort: a missing codesign (non-mac host, stripped CLT) is a warning."""
    if shutil.which("codesign") is None:
        log.warning("codesign not found — skipping ad-hoc signature")
        return
    proc = run_hidden(
        ["codesign", "--force", "--deep", "-s", "-", str(bundle)],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        log.warning("codesign failed: %s", (proc.stderr or "").strip())


def uninstall_app(applications: Path | None = None) -> bool:
    bundle = app_dir(applications)
    if not bundle.exists():
        return False
    shutil.rmtree(bundle)
    return True
